INSERT INTO TB_USER(EMAIL, PASSWORD) VALUES ('ana@gmail.com', '$2a$12$VtAex1HNaVZkgMJuzhgFGO7rd.BGYOrW67/Kp1N9ml6GpzXAJtNEC');
INSERT INTO TB_USER(EMAIL, PASSWORD) VALUES ('bob@gmail.com', '$2a$12$VtAex1HNaVZkgMJuzhgFGO7rd.BGYOrW67/Kp1N9ml6GpzXAJtNEC');

INSERT INTO TB_ROLE(AUTHORITY) VALUES ('ROLE_CLIENT');
INSERT INTO TB_ROLE(AUTHORITY) VALUES ('ROLE_ADMIN');

INSERT INTO TB_USER_ROLE(ID_USER, ID_ROLE) VALUES (1, 1);
INSERT INTO TB_USER_ROLE(ID_USER, ID_ROLE) VALUES (2, 1);
INSERT INTO TB_USER_ROLE(ID_USER, ID_ROLE) VALUES (2, 2);